# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnAUJnXqwDCCFudayyHbk_od-eYVD1Wc
"""

import json
from pathlib import Path

import joblib
import pandas as pd
import streamlit as st

st.set_page_config(
    page_title="Riesgo Actuarial con K-means",
    page_icon="📊",
    layout="centered"
)

MODEL_PATH = Path("models/kmeans_riesgo_actuarial.pkl")
META_PATH = Path("models/model_metadata.json")

@st.cache_resource
def cargar_modelo():
    modelo = joblib.load(MODEL_PATH)
    with open(META_PATH, "r", encoding="utf-8") as f:
        metadata = json.load(f)
    return modelo, metadata

modelo, metadata = cargar_modelo()

st.title("Clasificación de riesgo actuarial con K-means")
st.write(
    "Ingrese los datos del cliente. La aplicación asignará el cliente a un cluster "
    "y mostrará su nivel de riesgo actuarial estimado."
)

st.warning(
    "Este modelo usa K-means, un método no supervisado. El resultado es una segmentación "
    "orientativa, no una decisión actuarial definitiva."
)

st.subheader("Datos del cliente")

col1, col2 = st.columns(2)

with col1:
    age = st.number_input("Edad", min_value=18, max_value=100, value=40)
    bmi = st.number_input("Índice de masa corporal (BMI)", min_value=10.0, max_value=60.0, value=28.0)
    children = st.number_input("Número de hijos/dependientes", min_value=0, max_value=10, value=1)

with col2:
    sex = st.selectbox("Sexo", ["male", "female"])
    smoker = st.selectbox("¿Fuma?", ["no", "yes"])
    region = st.selectbox("Región", ["southwest", "southeast", "northwest", "northeast"])
    charges = st.number_input("Cargos médicos estimados", min_value=0.0, value=10000.0)

cliente = pd.DataFrame([{
    "age": age,
    "sex": sex,
    "bmi": bmi,
    "children": children,
    "smoker": smoker,
    "region": region,
    "charges": charges
}])

if st.button("Evaluar riesgo"):
    cluster = int(modelo.predict(cliente)[0])

    mapa_riesgo = metadata["mapa_riesgo"]
    riesgo = mapa_riesgo[str(cluster)]

    st.subheader("Resultado")
    st.metric("Cluster asignado", cluster)
    st.metric("Nivel de riesgo actuarial", riesgo)

    descripcion = metadata["descripcion_riesgo"].get(
        riesgo,
        "Cliente agrupado según similitud con otros perfiles."
    )

    if riesgo == "Alto":
        st.error(descripcion)
    elif riesgo == "Medio":
        st.warning(descripcion)
    else:
        st.success(descripcion)

    st.write("Datos evaluados:")
    st.dataframe(cliente)

st.divider()

st.subheader("Información del modelo")
st.write("Tipo de modelo:", metadata.get("tipo_modelo"))
st.write("Número de clusters:", metadata.get("n_clusters"))
st.write("Silhouette score:", metadata.get("silhouette_score"))
st.write(metadata.get("nota_metodologica"))